messages:
  - "Comment appelle-t-on une captapulte à salade ?


  Un lance roquette !!

  Aller bisous"

  - "Bonjour

  C'est un éléphant qui rentre dans un café, et plouf!!

  Bonne journée!"

  - "Bonjour!

  C'est 2 cookies dans un micro-onde, l'un dit:

  - Dis-donc, il fait chaud là dedans !

  - Oh mon dieu, un cookie qui parle !!!

  Aller salut l'équipe."

subject: "Une petite blagounette"