messages:
  - subject: "fruits et légumes"
    content: "Comment appelle-t-on une captapulte à salade ?


    Un lance roquette !!

    Aller bisous"

  - subject: "Visite au zoo"
    content: "Bonjour

    C'est un éléphant qui rentre dans un café, et plouf!!

    Bonne journée!"

  - subject: "Cuisine"
    content: "Bonjour!

    C'est 2 cookies dans un micro-onde, l'un dit:

    - Dis-donc, il fait chaud là dedans !

    - Oh mon dieu, un cookie qui parle !!!

    Aller salut l'équipe."

